"""常量和模板模块"""
from .templates import (
    FORMAT_GUIDE,
    STYLE_GUIDE,
    FOLLOW_UP_SUGGESTIONS,
    SYSTEM_PROMPT_TEMPLATE,
    TONE_LABELS,
    SCENE_LABELS,
    MOOD_LABELS,
    HERO_HTML_TEMPLATE,
    FOOTER_HTML_TEMPLATE,
    RECENT_CARD_TEMPLATE,
    RECENT_EMPTY_TEMPLATE,
    ANALYSIS_PILL_TEMPLATE,
)

__all__ = [
    "FORMAT_GUIDE",
    "STYLE_GUIDE",
    "FOLLOW_UP_SUGGESTIONS",
    "SYSTEM_PROMPT_TEMPLATE",
    "TONE_LABELS",
    "SCENE_LABELS",
    "MOOD_LABELS",
    "HERO_HTML_TEMPLATE",
    "FOOTER_HTML_TEMPLATE",
    "RECENT_CARD_TEMPLATE",
    "RECENT_EMPTY_TEMPLATE",
    "ANALYSIS_PILL_TEMPLATE",
]